# Aggregate Statistics

In [33]:
import pandas as pd 

df= pd.read_csv('pokemon_data.csv')

df.groupby(['Type 1']).mean().sort_values(['Defense'],ascending=False) #grouped by type 1 , find mean of defense based on group

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408

In [34]:
df.groupby(['Type 1']).sum() #grouped by type 1 , find sum of features based on group

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Bug,23080,3925,4897,4880,3717,4471,4256,222,0
Dark,14302,2071,2740,2177,2314,2155,2361,125,2
Dragon,15180,2666,3588,2764,3099,2843,2657,124,12
Electric,15994,2631,3040,2917,3961,3243,3718,144,4
Fairy,7642,1260,1046,1117,1335,1440,826,70,1
Fighting,9824,1886,2613,1780,1434,1747,1784,91,0
Fire,17025,3635,4408,3524,4627,3755,3871,167,5
Flying,2711,283,315,265,377,290,410,22,2
Ghost,15568,2062,2361,2598,2539,2447,2059,134,2
Grass,24141,4709,5125,4956,5425,4930,4335,235,3
Ground,11401,2361,3064,2715,1807,2008,2045,101,4
Ice,10165,1728,1746,1714,1861,1831,1523,85,2
Normal,31279,7573,7200,5865,5470,6245,7012,299,2
Poison,7050,1883,2091,1927,1692,1803,1780,71,0
Psychic,21706,4026,4073,3858,5609,4918,4645,193,14
Rock,17280,2876,4086,4435,2787,3321,2460,152,4
Steel,11957,1761,2503,3412,1823,2177,1492,104,4
Water,33946,8071,8305,8170,8379,7898,7388,320,4

In [35]:
df.groupby(['Type 1']).sum()['Attack'] #grouped by type 1 , find sum of attack based on group

Type 1
Bug         4897
Dark        2740
Dragon      3588
Electric    3040
Fairy       1046
Fighting    2613
Fire        4408
Flying       315
Ghost       2361
Grass       5125
Ground      3064
Ice         1746
Normal      7200
Poison      2091
Psychic     4073
Rock        4086
Steel       2503
Water       8305
Name: Attack, dtype: int64

In [40]:
df.groupby(['Type 1']).count()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,count
Type 1,,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27,27
Fire,52,52,24,52,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112,112

In [36]:
df['count']=1
df.groupby(['Type 1']).sum()['count']  #grouped by type 1 , find count of each group

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

In [39]:
df.groupby(['Type 1','Type 2']).sum()['count'] #grouped by type 1 then type 2 , find count of sub group

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64